# kubectl apply -f ms-clientes-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: ms-clientes-secret
  namespace: ms-clientes-namespace
type: Opaque
data:
  # echo -n "valor" | base64
  DB_HOST: "ZXAtcHJvdWQtZnJvc3QtYXQyaGtnOW0tcG9vbGVyLmM5LnVzLWVhc3QtMS5hd3MubmVvbi50ZWNo"
  DB_PORT: "NTQzMg=="
  DB_NAME: "Y2xpZW50ZXM="
  DB_USER: "bmVvbmRiX293bmVy"
  DB_PASSWORD: "bnBnX0pWYlBsMWNTczh4"
  DB_SSL_MODE: "cmVxdWlyZQ=="
  SERVER_PORT: "ODA4MA=="